/* Q: WHICH ACTORS (TOP 5) APPEAR IN THE MOST NUMBER OF FILMS */
SELECT FIRST_NAME AS "FIRST NAME", 
		LAST_NAME AS "LAST_NAME", 
		COUNT(FA.FILM_ID) AS "NUMBER OF FILMS" 
FROM ACTOR A JOIN FILM_ACTOR FA ON A.ACTOR_ID = FA.ACTOR_ID
GROUP BY A.ACTOR_ID 
ORDER BY COUNT(FA.FILM_ID) DESC
LIMIT 5; 

/*WHAT'S THE AVERAGE AMOUNT SPENT FOR EACH FILM CATEGORY? */ 
SELECT NAME AS " FILM TYPE", 
	   CONCAT('$',FORMAT(AVG(AMOUNT),2)) AS "AVG AMOUNT"
FROM CATEGORY C JOIN FILM_CATEGORY FC ON C.CATEGORY_ID = FC.CATEGORY_ID
JOIN FILM F ON FC.FILM_ID = F.FILM_ID
JOIN INVENTORY I ON F.FILM_ID = I.FILM_ID
JOIN RENTAL R ON I.INVENTORY_ID = R.INVENTORY_ID
JOIN PAYMENT P ON R.RENTAL_ID = P.RENTAL_ID
GROUP BY NAME
ORDER BY AVG(AMOUNT) DESC;

/* WHAT FILM CATEGORIES HAVE A TOTAL RENTAL RATE OF 170 OR LOWER? */ 
SELECT NAME AS "FILM TYPE", 
	   SUM(RENTAL_RATE) AS "TOTAL RENTAL RATE"
FROM CATEGORY C JOIN FILM_CATEGORY FC ON C.CATEGORY_ID = FC.CATEGORY_ID
JOIN FILM F ON FC.FILM_ID = F.FILM_ID
GROUP BY NAME
HAVING SUM(RENTAL_RATE) <= 170
ORDER BY SUM(RENTAL_RATE) ASC;

/* WHAT IS THE RANGE OF RENTAL RATES */ 
SELECT DISTINCT RENTAL_RATE
FROM FILM
ORDER BY RENTAL_RATE DESC;

/* WHAT DAY HAD THE HIGHEST AMOUNT OF SALES & HOW MUCH WAS IT? */ 
SELECT CAST(PAYMENT_DATE AS DATE) AS "DATE", 
	   CONCAT('$',FORMAT(SUM(AMOUNT),2)) AS "TOTAL SALES"
FROM PAYMENT
GROUP BY CAST(PAYMENT_DATE AS DATE)
ORDER BY SUM(AMOUNT) DESC
LIMIT 1; 

/* IN WHAT MONTH DID THE LEAST AMOUNT OF RENTALS TAKE PLACE? */ 
SELECT MONTH(CAST(RENTAL_DATE AS DATE)) AS "MONTH", COUNT(RENTAL_ID) AS "TOTAL RENTALS"
FROM RENTAL
GROUP BY MONTH(CAST(RENTAL_DATE AS DATE))
ORDER BY COUNT(RENTAL_ID) ASC
LIMIT 1; 

/* HOW MANY FILMS HAVE A RENTAL RATE OF .99, 2.99 & 4.99? */ 
SELECT COUNT(FILM_ID) AS "RENTAL RATE (.99)",
(SELECT COUNT(FILM_ID) FROM FILM WHERE RENTAL_RATE = 2.99) AS "RENTAL RATE (2.99)", 
(SELECT COUNT(FILM_ID) FROM FILM WHERE RENTAL_RATE = 4.99) AS "RENTAL RATE (4.99)"
FROM FILM 
WHERE RENTAL_RATE = .99; 

/* HOW MANY TOTAL RENTALS DOES EACH STORE HAVE? */ 
SELECT S.STORE_ID, COUNT(RENTAL_ID) AS "NUMBER OF RENTALS"
FROM STORE S JOIN CUSTOMER C ON S.STORE_ID = C.STORE_ID
JOIN RENTAL R ON C.CUSTOMER_ID = R.CUSTOMER_ID
GROUP BY S.STORE_ID
ORDER BY S.STORE_ID ASC;

/* WHAT'S THE TOTAL SALES FOR EACH STORE? */
SELECT S.STORE_ID, CONCAT('$',FORMAT(SUM(AMOUNT),2)) AS " TOTAL SALES"
FROM STORE S JOIN CUSTOMER C ON S.STORE_ID = C.STORE_ID
JOIN RENTAL R ON C.CUSTOMER_ID = R.CUSTOMER_ID
JOIN PAYMENT P ON R.RENTAL_ID = P.RENTAL_ID
GROUP BY S.STORE_ID;

/* WHAT CUSTOMERS HAVE THE GREATEST NUMBER OF RENTALS (TOP 10)? */ 
SELECT FIRST_NAME, LAST_NAME, COUNT(RENTAL_ID) AS "NUMBER OF RENTALS"
FROM CUSTOMER C JOIN RENTAL R ON C.CUSTOMER_ID = R.CUSTOMER_ID
GROUP BY R.CUSTOMER_ID
ORDER BY COUNT(RENTAL_ID) DESC
LIMIT 10; 

/* HOW MUCH DOES THE AVERAGE CUSTOMER SPEND? */  
SELECT CONCAT('$',FORMAT(AVG(AMOUNT), 2)) AS "AVG SPENT"
FROM PAYMENT; 

/*WHICH STAFF MEMBER HAD THE LEAST AMOUNT OF SALES VOLUME IN JULY OF 2005 & HOW MUCH WAS IT? */ 
SELECT FIRST_NAME, LAST_NAME, COUNT(PAYMENT_ID) AS "NUMBER OF SALES" 
FROM STAFF S JOIN PAYMENT P ON S.STAFF_ID = P.STAFF_ID
WHERE PAYMENT_DATE LIKE '%2005-07%'
GROUP BY P.STAFF_ID
ORDER BY COUNT(PAYMENT_ID) ASC
LIMIT 1; 

/*WHAT COUNTRIES HAVE THE GREATEST NUMBER OF CUSTOMERS (TOP 3)?*/ 
SELECT COUNTRY, COUNT(CUSTOMER_ID) AS "NUMBER OF CUSTOMERS"
FROM COUNTRY CO JOIN CITY C ON CO.COUNTRY_ID = C.COUNTRY_ID
JOIN ADDRESS A ON C.CITY_ID = A.CITY_ID
JOIN CUSTOMER CU ON A.ADDRESS_ID = CU.ADDRESS_ID
GROUP BY COUNTRY
ORDER BY COUNT(CUSTOMER_ID) DESC
LIMIT 3; 

/* IS THE FILM "CELEBRITY HORN" AVAILABLE @ STORE 1? */ 
SELECT DISTINCT (CASE WHEN I.STORE_ID = 1 THEN "YES" ELSE "NO" END) AS "DOES STORE 1 HAVE 'CELEBRITY HORN'?"
FROM FILM F JOIN INVENTORY I ON F.FILM_ID = I.FILM_ID 
WHERE I.STORE_ID = 1 AND TITLE LIKE "CELEBRITY HORN";

/* HOW MANY ACTION MOVIES ARE AVAILABLE? */
SELECT COUNT(F.FILM_ID) AS "ACTION FILMS AVAILABLE"
FROM CATEGORY C JOIN FILM_CATEGORY FC ON C.CATEGORY_ID = FC.CATEGORY_ID
JOIN FILM F ON FC.FILM_ID = F.FILM_ID
WHERE NAME = "ACTION"; 

/* WHAT'S THE MAXIMUM, MINIMUM & AVERAGE REPLACEMENT COST FOR A FILM? */ 
SELECT CONCAT('$',FORMAT(MAX(REPLACEMENT_COST),2)) AS "MAX COST", 
	   CONCAT('$',FORMAT(MIN(REPLACEMENT_COST),2)) AS "MIN COST", 
       CONCAT('$',FORMAT(AVG(REPLACEMENT_COST),2)) AS "AVG COST"
FROM FILM; 

/* WHAT'S THE TOTAL NUMBER OF NULL VALUES AND NOT NULL VALUES IN THE ADDRESS2 COLUMN (IN ADDRESS TABLE)? */ 
SELECT SUM(CASE WHEN ADDRESS2 IS NULL THEN 1 ELSE 0 END) AS "NULL", COUNT(ADDRESS2) AS "NOT NULL"
FROM ADDRESS; 